apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  namespace: kubernetes-dashboard
  labels:
    app: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      serviceAccountName: admin-user
      containers:
        - name: node-web-app
          image: bpritch/node-web-app
          ports:
            - containerPort: 3000