# node_web_app_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
  namespace: kubernetes-dashboard
spec:
  selector:
    app.kubernetes.io/name: node-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
